# Generated by Django 5.2.11 on 2026-03-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_userintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='slack_webhook_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
