# Generated by Django 5.2.11 on 2026-03-04 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_userintegration_slack_webhook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
