# Generated by Django 5.2.11 on 2026-03-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_dailyreport_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='teams_webhook_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
