# Generated by Django 5.2.11 on 2026-03-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_userintegration_teams_webhook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userintegration',
            name='teams_webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
