# Generated by Django 5.2.11 on 2026-03-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_reporttemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttemplate',
            name='template2',
        ),
    ]
