# Generated by Django 5.2.11 on 2026-03-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_remove_reporttemplate_template2'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='ai_memo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
