# Generated by Django 5.2.11 on 2026-03-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_dailyreport_ai_memo_dailyreport_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='gmail_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
